= Guide to Solving Tangle in Neo4j

=== How to get Started

* install docker and docker-compose

* create .env file using env.example as your guide

* enter the command docker-compose up from the root of the project this will start neo4j as well as a server to host our guide

* navigate to localhost:7474/browser and enter your user: 'neo4j' and password

* the guide should autoload if not type :guide http://localhost:8081/html/words.html in the noe4j browser window

If desired you can use the rest 

=== Converting Asciidoc Files to Neo4j Browser Guides

This program uses AsciiDoctor erb templates to generate an outline html and a slide for each level two header.

=== Create HTML

----
./run.sh path/to/a_guide.adoc [guide.html]

-> html/a_guide.html
----

Full options:

[source,shell]
----
./run.sh /path/to/file.adoc [/path/to/file.html] [header-level-offset] [base-url] [additional asciidoc options]

# for example for the recommendations sandbox-guide
./run.sh ../recommendations/documentation/recommendations.adoc \
         ../recommendations/documentation/recommendations.neo4j-browser-guide \
         +1 https://guides.neo4j.com/sandbox/recommendations -a neo4j-version=5.4 -a env-guide
----

To view the guides in the Neo4j Browser, run:

----
:play http://localhost:8001/html/a_guide.html
----

You can find more details on how to create guides and their format at portal.graphgists.com
